name: "Test"

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version:
          - 22.x

    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Use pnpm@9
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install
        run: |
          pnpm install --frozen-lockfile
      - name: Check pnpm-lock.yaml
        run: git diff --exit-code pnpm-lock.yaml
      - name: "Test"
        run: pnpx vitest --coverage.enabled true
      - name: "Report coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
